baseURL: "https://k7mfr.org/"
languageCode: "en-us"
title: "Rogue Valley Amateur Radio Club"
author: "K7RVM"
googleAnalytics: UA-147251318-1

menu:
  main:
  - identifier: "Club Info"
    name: "Club Info"
    url: /
    weight: 1